### ISSUE TITLE
Error: connect ETIMEDOUT 

### ISSUE THREAD

**Issue by autoferrit** [loopbackio/loopback-connector-postgresql#25]
If I simply run the command `slc run .` on a brand new app, I get the below output. The only thing I have done is install the connecter from this repo, use the loopback tutorial for creating a connector, then create a model using that connector.

Once I run the command, after about a minutes of either doing nothing, or even trying to use the app, I get this output:

``` bash
$ slc run .
supervisor running without clustering (unsupervised)
2014-08-16T09:12:49.615Z pid:45122 worker:supervisor INFO strong-agent dashboard is at https://strongops.strongloop.com
2014-08-16T09:12:49.618Z pid:45122 worker:supervisor INFO strong-agent using collector https://collector.strongloop.com:443
2014-08-16T09:12:49.618Z pid:45122 worker:supervisor INFO strong-agent v0.4.12 profiling app 'shinyredrobot.com' pid '45122'
2014-08-16T09:12:49.618Z pid:45122 worker:supervisor INFO strong-agent[45122] started profiling agent
Browse your REST API at http://localhost:3000/explorer
Web server listening at: http://localhost:3000/
2014-08-16T09:12:49.952Z pid:45122 worker:supervisor INFO strong-agent[45122] connected to collector
{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }

/www/projects/shinyredrobot/shinyredrobot.com/node_modules/loopback-connector-postgresql/lib/postgresql.js:105
      throw err;
            ^
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

here is my datasources.json:

``` json
{
  "db"          : {
    "name"     : "db",
    "connector": "memory"
  },
  "dev_redrobot": {
    "name"     : "dev_redrobot",
    "connector": "postgresql",
    "database" : "dev_redrobot",
    "username" : "myuser",
    "password" : "mypass"
  }
}
```

I followed the articles for getting started with loopback and didnt really have any issues. So I am not sure what I may be doing wrong. But I can't stay connected to the db. I also want to note, that before this timeout, the connection and the example models work fine. i can post data to the db using postman.

I am running Postgres 9.3, OSX 10.9, and node v0.10.28 and the slc command was just installed today. If there are any other logs or info I can provide, please let me know.

**Comment by jjhesk** [comment]
same issue to me, because im using local to turn on the connection to the postsql and it rejected me. I need to resolve this issue asap. thanks

**Comment by nicolasbatistoni** [comment]
Do you have any news? Were you able to solve your problem?
