### ISSUE TITLE
Custom property types or how to map model property to table column?

### ISSUE THREAD

**Issue by unibasil** [loopbackio/loopback-connector-postgresql#4]
Is there any way to define complex model property mapping to datasource table column and vice versa?  PostGIS (PostgreSQL GIS extention library) has sophisticated data types, `geometry` and `geography`, which are stored in table columns as packed strings of digits, so are not usable directly. To work with them via "REST API" way these types need to be converted _to_ and _from_ GeoJSON (specific type of JSON ) by PostGIS own functions `ST_AsGeoJSON(geom)` and `ST_GeomFromGeoJSON(geojson)`. So to get data from geometry-type column we need to run query

``` sql
SELECT ST_AsGeoJSON(geom) AS geom FROM table WHERE ...
```

and to update `geom` column the query would be

``` sql
UPDATE table SET geom = ST_GeomFromGeoJSON(geojson) WHERE ...
```

In [node-orm2](https://github.com/dresende/node-orm2) project this issue is solved by defining custom property type with `datastoreGet` and `datastoreSet` methods, what's about LoopBack project?

**Comment by amenadiel** [comment]
@raymondfeng are these indications still valid?

Editing the connector native library sounds like a bad practice. Is it possible to use registerType from outside, like for example before booting the application?
It sounds like a

**Comment by topalavlad** [comment]
Are there any updates on this?

**Comment by unibasil** [comment]
I personally think that was "one million (or even billion) $ mistake" for StrongLoop, when they choosed JugglingDB for their system ORM. JDB was terrible and even now nothing can be done with initial architectual faults. Pity, other LoopBack aspects are very good...

**Comment by always-akshat** [comment]
based upon @raymondfeng 's suggestions,  I have created a new [type](https://bitbucket.org/snippets/always_akshat/Mq4qe) which allows you to access Geometry Datatype from mysql. It will provide data in array of objects or array of array of objects depending upon the entered value's type (LineString, Polygon).

**Comment by jbcpollak** [comment]
I'm interested in doing something like this with PostGIS and GeoJSON

**Comment by devpascoe** [comment]
@jbcpollak yes please! :)

**Comment by alexander-rusanov** [comment]
Any updates on it? We will use google services for address autocompletion and it will give us lat/lng and then we need to save that in postgres table with postgis point type (for future calculations). It seems i need to override each loopback CRUD method where geo data will be passed back and forth with my own code and use plain SQL to transform data from google to postgis and vice versa. Please tell me me i'm wrong and there is already working solution :)

**Comment by amenadiel** [comment]
I gave up on this long ago and just handle geometries back and forth using wkx library
 
https://www.npmjs.com/package/wkx
