### ISSUE TITLE
Postgres support > 9.x

### ISSUE THREAD

**Issue by pydotjs** [loopbackio/loopback-connector-postgresql#472]
## Suggestion

I note in the readme that either Postgres 8 or 9 is required for the connector. Is there compatibility / a solution or pathway for newer Postgres versions?

## Use Cases

I've been notified by AWS that RDS with Postgres 9.x will be EOL by November 11th, 2021. They are recommending shifting to Postgres 12 (a significant jump) and will make the transition forced by February 22nd, 2022.

**Comment by pydotjs** [comment]
UPDATE

I've hooked up my project with:
- Postgres v12.5 (coming from v9.6)
- connector v5.3.0 (coming from v3.6.1)
- loopback v3

It is ostensibly behaving as a drop-in replacement for my existing versions, so I'm assuming the readme has not been updated for newer postgres compatibility.

**Comment by dhmlau** [comment]
I'm using postgres 11.5 in my docker image and it's been running fine. 
Travis CI is using 9.6 though. There's an effort to use GitHub Actions for our CI instead. If you're interested to help for this connector, please feel free! Here is a reference for the mongodb connector: https://github.com/strongloop/loopback-connector-mongodb/pull/613.
