### ISSUE TITLE
If url is empty string in config server crashes

### ISSUE THREAD

**Issue by mlakdawala-sf** [loopbackio/loopback-connector-postgresql#504]
## Current Behavior
If url prop is set to "" the server crashes

## Expected Behavior

It should be backward compatible, setting url:"" used to work previously 
It stopped working post (https://github.com/loopbackio/loopback-connector-postgresql/commit/1a863f3df332f1732e8fec519f1d686561313a3e)

**Comment by sonythr** [comment]
Experience the same behavior, for now I to use the previous one while waiting for the update

**Comment by sonythr** [comment]
Hi @achrinza I still got the same error, and npm still have the latest version as 5.5.1. It seems 5.5.2 is not there yet
