### ISSUE TITLE
Add back Node.js v12 tests

### ISSUE THREAD

**Issue by achrinza** [loopbackio/loopback-connector-postgresql#520]
Dropping support would be considered a breaking change. Until we agree to do a server major bump (e.g. with other breaking changes), we should continue testing older versions of Node.js.

**Comment by dhmlau** [comment]
With Node.js 12 EOL April 2022, it makes sense to drop the support. My question would be whether we want to wait till next April so Node.js 14 to go EOL, then we have a major version bump at that time. 

Reference: Node.js LTS schedule https://github.com/nodejs/Release

**Comment by samarpanB** [comment]
I can do this change as part of my PR here - https://github.com/loopbackio/loopback-connector-postgresql/pull/524. Let me know what you guys think ? @achrinza @dhmlau

**Comment by achrinza** [comment]
@samarpanB Im ok with that 👍

**Comment by samarpanB** [comment]
Closing since node12 support has been dropped now.
